export default {
    'blue': '#0275d8',
    'dark': '#292b2c',
    'darkBlue': '#001e38',
    'darkGray': 'darkgray',
    'darkGreen': '#032d29',
    'darkPokedex': '#810a1e',
    'darkred': 'darkred',
    'dimGray': 'dimGray',
    'firebrick': 'firebrick',
    'gray': 'gray',
    'light': '#dedede',
    'lightBlue': '#31a7f1',
    'lightGray': 'lightGray',
    'lightGreen': '#55ab62',
    'pokedex': '#ce1131',
    'red': 'red',
    'sky': '#5bc0de',
    'white': 'white',
    'yellow': '#f0ad4e',
}
