export default {
    'blue': '#0275d8',
    'dark': '#292b2c',
    'darkGreen': '#032d29',
    'darkPokedex': '#810a1e',
    'darkred': 'darkred',
    'firebrick': 'firebrick',
    'light': '#dedede',
    'lightBlue': '#31a7f1',
    'lightGreen': '#55ab62',
    'pokedex': '#ce1131',
    'red': 'red',
    'sky': '#5bc0de',
    'yellow': '#f0ad4e',
}
